// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFLe2GGNx3ItMYzt1fjoYILxxejmvralI',
    appId: '1:715002392272:web:ab159e966bd1e2e9f178d5',
    messagingSenderId: '715002392272',
    projectId: 'tech4girls-8e9d4',
    authDomain: 'tech4girls-8e9d4.firebaseapp.com',
    storageBucket: 'tech4girls-8e9d4.firebasestorage.app',
    measurementId: 'G-6HL3JWEXL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXhywRSgXZW1jyg3x0FsPISK8esbCap-o',
    appId: '1:715002392272:android:b2b7b03bd4888376f178d5',
    messagingSenderId: '715002392272',
    projectId: 'tech4girls-8e9d4',
    storageBucket: 'tech4girls-8e9d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1u4f2jz2d13GO1_-ktQFWviHrz0xd9Fo',
    appId: '1:715002392272:ios:9aae113763d50ea5f178d5',
    messagingSenderId: '715002392272',
    projectId: 'tech4girls-8e9d4',
    storageBucket: 'tech4girls-8e9d4.firebasestorage.app',
    iosBundleId: 'com.example.tech4girls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1u4f2jz2d13GO1_-ktQFWviHrz0xd9Fo',
    appId: '1:715002392272:ios:9aae113763d50ea5f178d5',
    messagingSenderId: '715002392272',
    projectId: 'tech4girls-8e9d4',
    storageBucket: 'tech4girls-8e9d4.firebasestorage.app',
    iosBundleId: 'com.example.tech4girls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFLe2GGNx3ItMYzt1fjoYILxxejmvralI',
    appId: '1:715002392272:web:5a885d37ebab9ca3f178d5',
    messagingSenderId: '715002392272',
    projectId: 'tech4girls-8e9d4',
    authDomain: 'tech4girls-8e9d4.firebaseapp.com',
    storageBucket: 'tech4girls-8e9d4.firebasestorage.app',
    measurementId: 'G-Z84RQR8YL9',
  );
}
